version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
