# Generated by Django 2.0.7 on 2018-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('function', models.CharField(choices=[('stringClean', 'stringClean'), ('maxBlock', 'maxBlock'), ('reorderBlock', 'reorderBlock')], default='', max_length=25)),
                ('input_string', models.TextField()),
                ('result', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
